# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa4855478414a133d49ab8f13c8a7deb26c8b66ba8f9a1e51e269fd533d6daa06a7bf039667d0d590ae6856f95bef06b4c070864ed1d5b0ab611c765d4077e72

test:
  secret_key_base: 4f24ecf44136e04a67ca94d8624eaed6f66dee94be05b16214bb819dde98222c4c215c13188c93812da8a0488277d52f6dd5b131d4c174f8ac596a6172e419df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
